name: Build

on:
  push:
  pull_request:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        arch: [x86_64]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - uses: olegtarasov/get-tag@v2.1.4
      id: tagName

    - name: Setup xmake
      uses: xmake-io/github-action-setup-xmake@v1
      with:
        xmake-version: branch@dev

    - name: Tests
      run: |
        xmake
        xmake b tests
        xmake run tests

    - name: Create release bundle
      run: |
        xmake install -o artifacts

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: synctignore.${{ matrix.os }}.${{ matrix.arch }}
        path: artifacts

    - name: Upload to release
      if: github.event_name == 'release'
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: ${{ matrix.os == 'windows' && 'artifacts/bin/synctignore.exe' || 'artifacts/bin/synctignore' }} 