name: Build

on:
  push:
  pull_request:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: runner.arch == 'X64'

    steps:
    - uses: actions/checkout@v4

    - uses: olegtarasov/get-tag@v2.1.4
      id: tagName

    - name: Setup Cosmocc
      uses: bjia56/setup-cosmocc@main
      with:
        version: "4.0.2"

    - name: Setup xmake
      uses: xmake-io/github-action-setup-xmake@v1
      with:
        xmake-version: branch@dev

    - name: Build project
      run: |
        xmake f -p linux --toolchain=cosmocc -y -cvD
        xmake

    - name: Tests
      run: |
       xmake b tests
       xmake run tests

    - name: Create release bundle
      run: |
        xmake install -o installfolder
        cd installfolder && zip -r ../synctignore.zip .

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: synctignore.cosmocc.x86_64
        path: installfolder # Upload artifact already create a zip file

    - name: Upload to release
      if: github.event_name == 'release'
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: synctignore.zip
        asset_name: synctignore-${{ steps.tagName.outputs.tag }}.zip
        asset_content_type: application/zip
